name: product-analytics-challenge
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - pyarrow
  - duckdb
  - duckdb-engine
